app: react-7ajs9w
env: staging
namespace: staging
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.61.0
values:
  image:
    repository: myappdvdv
strategicMergePatches: ""
json6902Patches: []
manifests: ""
